spring:
  r2dbc:
    url: r2dbc:mysql://47.115.52.56:3306/simons-gpt?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    name: simons-gpt
    pool:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null

logging:
  file:
    path: /home/ecs-user/logs

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "shutdown,health,info,metrics,loggers,threaddump,heapdump"

openai:
  endpoint: "https://openai-proxy-openai-proxy-tfbdvcgwxp.us-west-1.fcapp.run/v1"
  key: ${OPENAI_KEY}
  retry: 3

jwt:
  expiration: 86400000