spring:
  r2dbc:
    url: r2dbc:pool:mssql://simons-gpt.database.windows.net:1433
    username: ${AZURE_SQL_USERNAME}
    password: ${AZURE_SQL_PASSWORD}
    name: simons-gpt
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null

logging:
  file:
    path: logs

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "shutdown,health,info,metrics,loggers,threaddump,heapdump"

openai:
  endpoint: "https://api.openai.com/v1"
  # set the key from Azure Web Apps configuration
  key: ${OPENAI_KEY}
  retry: 3

jwt:
  expiration: 86400000