spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/simons-gpt?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}
    pool:
      enabled: false

#logging:
#  level:
#    root: debug