openapi: 3.0.0
info:
  title: OpenAI Wrapper API
  description: API for interacting with OpenAI's services, managing assistants, and user accounts.
  version: 1.0.0

servers:
  - url: 'https://127.0.0.1:8080/backend'

tags:
  - name: users
    description: User management
  - name: chat
    description: Chat with default model
  - name: assistants
    description: Assistant management
  - name: threads
    description: Chat thread management

paths:
  /users/register:
    post:
      summary: Register a new user
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '201':
          description: User created
        '400':
          description: Bad request

  /users/login:
    post:
      summary: Login a user
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: User logged in
          headers:
            Set-Cookie:
              schema:
                type: string
                example: session-token=abc123; Path=/; HttpOnly
        '401':
          description: Unauthorized

  /chat:
    post:
      summary: Send a message to the default model
      tags:
        - chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
      responses:
        '200':
          description: Message sent
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        '400':
          description: Bad request

  /assistants:
    get:
      summary: List all assistants
      tags:
        - assistants
      responses:
        '200':
          description: A list of assistants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Assistant'

  /threads:
    post:
      summary: Create a new chat thread with a specific assistant
      tags:
        - threads
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - assistantId
              properties:
                assistantId:
                  type: string
      responses:
        '201':
          description: Chat thread created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatThread'
        '400':
          description: Bad request

    get:
      summary: List all chat threads for the logged-in user
      tags:
        - threads
      responses:
        '200':
          description: A list of chat threads
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatThread'

  /threads/{threadId}:
    delete:
      summary: Delete a specific chat thread
      tags:
        - threads
      parameters:
        - name: threadId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Chat thread deleted
        '404':
          description: Not found

  /threads/{threadId}/messages:
    post:
      summary: Send a message to an assistant in a specific chat thread
      tags:
        - threads
      parameters:
        - name: threadId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
      responses:
        '201':
          description: Message sent
        '400':
          description: Bad request

components:
  schemas:
    Assistant:
      type: object
      properties:
        id:
          type: string
        object:
          type: string
        created_at:
          type: integer
          format: timestamp
        name:
          type: string
        description:
          type: string
          nullable: true
        model:
          type: string
        instructions:
          type: string
        tools:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
        file_ids:
          type: array
          items:
            type: string
        metadata:
          type: object
          additionalProperties: true
      required:
        - id
        - object
        - created_at
        - name
        - model
        - instructions

    ChatThread:
      type: object
      properties:
        id:
          type: string
        assistantId:
          type: string
        createdAt:
          type: string
          format: date-time
