name: Build and deploy JAR app to Aliyun ECS - simons-gpt

env:
  WEBAPP_NAME: simons-gpt       # set this to the name of your Web App
  JAVA_VERSION: '17'                  # set this to the Java version to use
  DISTRIBUTION: temurin               # set this to the Java distribution
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WEBAPP_NAME }}
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.WEBAPP_NAME }}

      - name: Deploy to Aliyun ECS
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SSH_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "*.jar"
          REMOTE_HOST: ${{ secrets.ALIYUN_REMOTE_HOST }}
          REMOTE_USER: ecs-user
          TARGET: "/home/ecs-user/simons-gpt"
          SCRIPT_BEFORE: |
            systemctl --user stop simons-gpt.service
          SCRIPT_AFTER: |
            systemctl --user start simons-gpt.service